fix creator hash js fn for bubblegum
metaplex-foundation/metaplex-program-library pull request #1064
Opened 2023-04-16 13:20 UTC by ilmoi

I found that the current function only works for 0 or 1 creators
once you go to 2 or more it fails to generate the correct creator hash, which leads to account_compression::verify_leaf failing

the test currently has an empty array of Creator[] which is why this fell through the cracks, unless I'm missing something ofc

2023-04-17 23:00 UTC, danenbm submitted a review, later dismissed

2023-04-18 06:33 UTC, lorisleiva requested changes
Thanks for that! I'm not too familiar with this repo but it does look like a valid bug fix. Would you be able to add a quick regression test that used to fail before this PR but now passes?

2023-04-18 06:33 UTC, lorisleiva commented on bubblegum/js/src/mpl-bubblegum.ts
> -    bufferOfCreatorShares = Buffer.concat([bufferOfCreatorShares, Buffer.from([creator.verified ? 1 : 0]), Buffer.from([creator.share])]);
Strange, it looks like this variable was never actually used within the function.

2023-04-26 20:26 UTC, danenbm commented
> Thanks for that! I'm not too familiar with this repo but it does look like a valid bug fix. Would you be able to add a quick regression test that used to fail before this PR but now passes?

Seems like we can just add some creators in one of the tests so that it exercises that hashing function in the test.  I tried doing it briefly but having some other issue at the moment and will come back to it unless you add the test @ilmoi before I get to it
```
    let creators: Creator[] = [
      {
        address: payer.publicKey,
        share: 55,
        verified: false,
      },
      {
        address: new Keypair().publicKey,
        share: 45,
        verified: false,
      },
    ]
```

2023-04-27 21:15 UTC, danenbm commented
> > Thanks for that! I'm not too familiar with this repo but it does look like a valid bug fix. Would you be able to add a quick regression test that used to fail before this PR but now passes?
> 
> Seems like we can just add some creators in one of the tests so that it exercises that hashing function in the test. I tried doing it briefly but having some other issue at the moment and will come back to it unless you add the test @ilmoi before I get to it
> 
> ```
>     let creators: Creator[] = [
>       {
>         address: payer.publicKey,
>         share: 55,
>         verified: false,
>       },
>       {
>         address: new Keypair().publicKey,
>         share: 45,
>         verified: false,
>       },
>     ]
> ```

I added this code above which exercises the function for 2 creators.  It causes a test failure before this PR's changes, and passes with the commits from this PR.

2023-04-28 06:34 UTC, lorisleiva approved these changes
Thanks Michael!

2023-04-28 17:58 UTC, samuelvanderwaal submitted a review, later dismissed

2023-04-30 22:11 UTC, samuelvanderwaal approved these changes

2023-05-01 20:07 UTC, danenbm approved these changes
I added test as well.  LGTM

2023-05-01 20:16 UTC, merged