Feature/membership token merge
metaplex-foundation/metaplex-program-library pull request #165
Opened 2022-01-27 12:54 UTC by bezrazli4n0

2022-01-28 08:56 UTC, VadimGrozinok requested changes

2022-01-28 08:56 UTC, VadimGrozinok commented on membership-token/cli/Cargo.lock
> +# This file is automatically @generated by Cargo.
Not sure that we need .lock for CLI

2022-01-31 09:37 UTC, VadimGrozinok approved these changes

2022-02-01 09:18 UTC, bezrazli4n0 commented
> SPL token has changes in 3.3.0 which will require solana tools 1.9.5 which will need solana-client 1.10 its a mess but since this is a new contract lets make sure we are at the newest you may need to take this out of the workspace.

I think `spl_token` version is blocked at `3.2.0`, because [solana-account-decoder](https://github.com/solana-labs/solana/blob/551c24da5792f4452c3c555e562809e8c9e742e5/account-decoder/Cargo.toml#L25) in `solana_client` force it.

2022-02-01 13:16 UTC, VadimGrozinok submitted a review, later dismissed

2022-02-04 01:24 UTC, merged