Reduce Gateway Compute (candy machine)
metaplex-foundation/metaplex-program-library pull request #325
Opened 2022-03-22 17:19 UTC by stegaBOB

Removes deserialization in favor of new CPI with eval into gateway

2022-03-23 17:14 UTC, stegaBOB commented
@buzzec

2022-03-23 17:15 UTC, Buzzec commented
Comment

2022-03-23 17:39 UTC, Buzzec requested changes

2022-03-23 17:39 UTC, Buzzec commented on candy-machine/program/src/lib.rs
> +
Replace this with a closure that you will then pass in as an eval function. Something like 
```rust
let eval_function = |token| match (&candy_machine.data, token.expire_time()) {
    (
        CandyMachineData {
            go_live_date: Some(go_live_date),
            whitelist_mint_settings: Some(WhitelistMintSettings { presale, .. }),
            ..
        },
        Some(expire_time),
    ) if presale && expire_time < go_live_date + EXPIRE_OFFSET => {
        Err(ErrorCode::GatewayTokenExpireTimeInvalid.into())
    }
    _ => Ok(()),
};
```

2022-03-23 17:39 UTC, Buzzec commented on candy-machine/program/src/lib.rs
> +                match min_go_live_date {
Remove this match and just pass in the eval function

2022-03-23 17:39 UTC, Buzzec commented on candy-machine/program/src/lib.rs
> +                match min_go_live_date {
Remove this match and just pass in the eval function

2022-05-05 23:37 UTC, stegaBOB commented
Closing this in favor of #418

2022-05-05 23:37 UTC, closed without merging