Adding an example auctioneer program for timed auctions.
metaplex-foundation/metaplex-program-library pull request #427
Opened 2022-05-02 18:47 UTC by blockiosaurus

2022-05-17 02:33 UTC, roederw commented on auction-house/program/src/auctioneer/update.rs
> +pub struct UpdateAuctioneer<'info> {
Are we still keeping this? @samuelvanderwaal @blockiosaurus

2022-05-17 02:33 UTC, roederw commented on auction-house/program/src/bid/mod.rs
> +pub fn auction_bid_logic<'info>(
`auctioneer_bid_logic`

2022-05-17 02:33 UTC, roederw commented on auction-house/program/src/delegate/mod.rs
> +
Can we nuke this file?

2022-05-17 02:33 UTC, roederw commented on auction-house/program/src/execute_sale/mod.rs
> +fn execute_auction_sale_logic<'info>(
`execute_auctioneer_sale_logic`

I know you're adding `Timed Auctions` with this change. Does it make sense to keep the "auction" wording here? Or does "auctioneer" make more sense. Your call.

2022-05-17 02:33 UTC, roederw commented on auction-house/program/src/state.rs
> +pub struct Auctioneer {
I'm going to see if there is a way to specify new `trade_states` in an `Auctioneer` instance, and pull them down. If not, we need to use `ListingConfig` for feature expansion. I'll try and look at this tonight.

2022-05-17 02:33 UTC, roederw commented on auctioneer/program/src/lib.rs
> +//pub const PREFIX: &str = "auctioneer";
Drop?

2022-05-17 02:33 UTC, roederw commented on auction-house/program/src/utils.rs
> +    AuctionPublicSale,
`AuctioneerPublicSale`?

Applies to all below.

2022-05-17 02:33 UTC, roederw commented on auctioneer/program/src/sell/config.rs
> +pub struct ListingConfig {
Are we adding floor price for listing when it's a Timed Bid?

2022-05-17 02:35 UTC, roederw commented
I skipped tests for now, will review them in more detail once you finish cleaning up and we're in a "ready to ship" state. There are a couple of things I'd like to investigate, but I don't want to block you. These changes are things we could add afterwards, that doesn't impact backwards compatibility. Going to think on it, and sync with you in the AM. I like this direction although the `trade_state` limitations are still annoying. Not sure if we can solve it gracefully.

2022-05-20 14:28 UTC, blockiosaurus commented
> Do you plan to get conflicts fixed before you want me to finish review?

Yeah, let me fix the conflicts and clean up. I just wanted to make sure you didn't notice any red flags in the initial PR.

2022-05-27 00:15 UTC, blockiosaurus commented on auction-house/program/src/execute_sale/mod.rs
> +    buyer_price: u64,
No, we have the dummy u64::MAX for that. So anything can be matched.

2022-05-27 00:16 UTC, blockiosaurus commented on auctioneer/program/src/execute_sale/mod.rs
> +
Ah I missed that. Added now.

2022-05-27 00:16 UTC, blockiosaurus commented on auctioneer/program/src/sell/config.rs
> +    pub amount: u64,
So in the bid as well as in the ListingConfig?

2022-06-07 19:51 UTC, samuelvanderwaal requested changes

2022-06-07 19:51 UTC, samuelvanderwaal commented on auction-house/program/src/execute_sale/mod.rs
> +        msg!("Here 2");
Remove this

2022-06-07 19:51 UTC, samuelvanderwaal commented on auction-house/program/src/execute_sale/mod.rs
> +        msg!("Here 1");
Remove this

2022-06-07 19:51 UTC, samuelvanderwaal commented on auction-house/program/src/execute_sale/mod.rs
> +    msg!("Here 0");
Remove this

2022-06-07 19:51 UTC, samuelvanderwaal commented on auctioneer/js/LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Fill this out

2022-06-07 19:57 UTC, samuelvanderwaal approved these changes

2022-06-07 20:09 UTC, merged