[Clippy Requirements] Adding the required changes to enable fmt/clippy requirements for Auction House
metaplex-foundation/metaplex-program-library pull request #468
Opened 2022-05-18 21:55 UTC by roederw

2022-05-18 21:58 UTC, NostalgicGareth approved these changes

2022-05-18 22:12 UTC, NostalgicGareth submitted a review, later dismissed

2022-05-19 18:37 UTC, samuelvanderwaal requested changes

2022-05-19 18:37 UTC, samuelvanderwaal commented on auction-house/program/src/auctioneer/delegate.rs
> +    scopes: Vec<AuthorityScope>,
interesting

2022-05-19 18:40 UTC, roederw commented on .clippy.toml
> +too-many-arguments-threshold = 20
no comment.

2022-05-19 18:45 UTC, samuelvanderwaal approved these changes

2022-05-19 21:44 UTC, blockiosaurus approved these changes

2022-05-19 21:51 UTC, merged