CHORE: add clippy to candy machine
metaplex-foundation/metaplex-program-library pull request #490
Opened 2022-05-26 18:26 UTC by stegaBOB

2022-05-26 19:43 UTC, samuelvanderwaal approved these changes

2022-05-27 16:55 UTC, roederw submitted a review, later dismissed

2022-05-30 15:46 UTC, thlorenz requested changes
If you could please update anchor and get the IDL fixed to include errors so we can generate those again with solita.
Also you should probably run the generator in any case  + include with this PR(unless the IDL just got reordered and results in same generated code).

I'm fine if the anchor upgrade needs to happen in a separate PR and will approve if this is too tricky to include here.

2022-05-30 15:46 UTC, thlorenz commented on candy-machine/js/idl/candy_machine.json
>        }
What I'm noticing here is that errors still didn't get fixed.
Couldn't we upgrade to anchor 0.24 to get those proper again?

2022-05-30 15:46 UTC, thlorenz commented on candy-machine/program/tests/core/helpers.rs
> +use std::str::FromStr;
I like those helpers.
Maybe it's time to pull those into a separate crate we can use all over? 
Maybe `sol-test-utils` or something like that for the solana core specific ones?
And `mp-test-utils` for the ones involving metaplex programs?

2022-05-30 16:29 UTC, thlorenz commented on candy-machine/js/idl/candy_machine.json
>        }
Actually confirmed that errors were indeed already fixed https://github.com/metaplex-foundation/metaplex-program-library/blob/cf472e24686f997eceefc7306b89dd9ea326222a/candy-machine/js/idl/candy_machine.json#L693

2022-05-30 16:29 UTC, thlorenz approved these changes
LGTM now :)

2022-05-30 20:22 UTC, merged