(feat) Adds Collections, Token Standards, Uses, Deprecations, Removals for V 1.1.0
metaplex-foundation/metaplex-program-library pull request #63
Opened 2022-01-08 10:09 UTC by austbot

2022-01-08 17:12 UTC, bhgames requested changes
Lots of little nitpicks and some architectural questions, but overall very good work.

You still need to add a use_item endpoint that decrements uses and/or burns if it's the last use, unless I missed that.

2022-01-08 17:12 UTC, bhgames commented on token-metadata/program/src/processor.rs
> +    if let Some(collection) = &mut metadata.collection {
may as well collapse this statement into the above match, no?

2022-01-08 17:12 UTC, bhgames commented on token-metadata/program/src/utils.rs
> +        uses: master_metadata.uses,
You need to make a new uses where the starting uses == the max available so the limited edition gets a fresh start

2022-01-08 17:12 UTC, bhgames commented on token-metadata/program/src/utils.rs
> +        name: data.name,
can likely replace this with your to_v1 code

2022-01-08 17:12 UTC, bhgames commented on token-metadata/program/src/utils.rs
> +    assert_valid_use(&data.uses, &None)?;
you can also bend this into assert valid data

2022-01-08 17:12 UTC, bhgames commented on token-metadata/program/src/utils.rs
> +        metadata.token_standard = None;
Under no circumstance should this be none going forward. You can always figure out what it is given mint info.

2022-01-08 17:32 UTC, aheckmann commented on token-metadata/program/src/assertions/uses.rs
> +        }
Do we care about validating changes to `uses` here?

2022-01-08 17:32 UTC, aheckmann commented on token-metadata/program/src/assertions/uses.rs
> +            Err(MetadataError::InvalidUseMethod.into())
Developers would appreciate more detail about why the data is invalid so they know how to fix the issue

2022-01-08 19:58 UTC, aheckmann commented on token-metadata/program/src/assertions/uses.rs
> +        }
Maybe I am misreading but doesn't this only match when `current_use`  is None? If there is currently a `use`, I'm thinking it'd be good to handle that validation here also

2022-01-09 01:21 UTC, samuelvanderwaal commented
Seems like it's missing a `create_collection` handler for actually creating the collection PDA.

2022-01-09 01:27 UTC, samuelvanderwaal commented on token-metadata/program/src/state.rs
> +pub struct Collection {
This should have `uri`, `name` and `num_item` fields as well.

`uri` for link to external JSON metadata scheme for Collection (image, description)

`name` for collection name

`num_items` for the number of items in the collection

2022-01-11 04:41 UTC, roederw approved these changes

2022-01-11 05:46 UTC, roederw commented
Ship it

2022-01-11 05:47 UTC, roederw approved these changes

2022-01-11 06:20 UTC, roederw approved these changes

2022-01-11 06:21 UTC, roederw commented
Deploy to Devnet. We don't need the packs test to move forward with that.

2022-01-11 19:41 UTC, aheckmann commented on token-metadata/program/src/pda.rs
> +pub fn find_medata_account(mint: &Pubkey) -> (Pubkey, u8) {
```suggestion
pub fn find_metadata_account(mint: &Pubkey) -> (Pubkey, u8) {
```

2022-01-11 23:49 UTC, roederw approved these changes

2022-01-12 00:11 UTC, merged