Adding some minor refactors to TM TokenMetadataAccount trait
metaplex-foundation/metaplex-program-library pull request #722
Opened 2022-09-06 20:59 UTC by blockiosaurus

Making TokenMetadataAccount trait more flexible.

2022-09-06 22:09 UTC, samuelvanderwaal approved these changes

2022-09-07 11:43 UTC, alexandruag commented on token-metadata/program/src/state.rs
> +        (data[0] == data_type as u8 || data[0] == Key::Uninitialized as u8)
As a general mention, I think the `as` operator should be avoided whenever possible; contrary to the core philosophy of the language, it quietly allows all sort of potentially dangerous casts, including (but not limited) to stuff like lossy narrowing of types. While a bit more verbose, I think it's better to perform conversions via specific methods (or implementations of traits like `From/Into`; or fallible stuff like `try_...` which return results if it's possible in any way to have failures).

2022-09-07 11:43 UTC, alexandruag commented on token-metadata/program/src/state.rs
> +        let result: Self = Self::deserialize(&mut data)?;
Just wondering, does `let result = Self::deserialize(&mut data)?;` also work here  (and in the similar situation below)?

2022-09-07 18:06 UTC, danenbm requested changes

2022-09-07 19:09 UTC, danenbm commented on token-metadata/program/src/state.rs
> +        let ua: Self = Self::safe_deserialize(&a.data.borrow_mut())
Nit: was this `ua:  Self` still needed now that safe deserialize specifically returns `Result<Self, BorshError>`?

2022-09-07 19:15 UTC, danenbm approved these changes
Looks great to me!

2022-09-07 19:31 UTC, merged